### ISSUE TITLE
I'm getting an error when try to make the sample

### ISSUE THREAD

**Issue by Klairm** [orbisdev/samples#14]
Hello! When i try to compile the orbis_gl sample 

 

>make
>Makefile:16: /usr/local/orbisdev//toolchain/bin//make/ps4sdk.mk: No existe el fichero o el >directorio
>make: *** No hay ninguna regla para construir el objetivo '/usr/local/orbisdev//toolchain/bin//make/ps4sdk.mk'.  Alto.

This is how i have the paths:
>export PATH=${DEVKITPRO}/tools/bin:${PS4SDK}:$PATH
>export PS4DEV=/usr/local/orbisdev/
>export PS4SDK=$PS4DEV/toolchain/bin/

**Comment by masterzorag** [comment]
retry removing trailing slash from the end of your paths:
```sh
export PS4DEV=/usr/local/orbisdev
export PS4SDK=$PS4DEV/toolchain/bin
```

**Comment by Klairm** [comment]
same

**Comment by psxdev** [comment]
https://github.com/psxdev/ps4sdk/tree/firmware505

Check readme. Some steps for make folder explained.

You have wrong configuration. Your fisrt export should be the last one. PATH has undefined PS4SDK value.
